### PR TITLE
Fix minor typos on README

### PR DESCRIPTION
**Pull request by Willboom**

### CODE REVIEW

**Comment by Stanley-GF** [comment]
https://www.youtube.com/watch?v=KAxWUz21sBE

**Comment by Willboom** [comment]
> https://www.youtube.com/watch?v=KAxWUz21sBE

I stole that video just like many did with your project, hope you don't mind

**Comment by Stanley-GF** [comment]
i dgaf

**Comment by Willboom** [comment]
> i dgaf

Nice :+1:

**Comment by PermisosDev** [comment]
+1 MERGE THIS!! i need this funtionality

**Comment by Stanley-GF** [comment]
image

**Comment by PermisosDev** [comment]
> image


> image

imagen
me?

**Comment by Willboom** [comment]
> image

Well I honestly prefer being a clown than having to distribute token grabbers as a living.

**Comment by Stanley-GF** [comment]
yeah yeah go cry babe

**Pull request closed without merging**
